name: Build APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodni yuklab olish
        uses: actions/checkout@v3

      - name: Java 17 o'rnatish
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle*') }}

      - name: gradlew ruxsat
        run: chmod +x gradlew

      - name: APK yigish
        run: ./gradlew assembleDebug --no-daemon

      - name: APK saqlash
        uses: actions/upload-artifact@v3
        with:
          name: SmartCarControl-APK
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30
